config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  resources :products
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3 }
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    http_basic_authenticate_with name: "mycloud", password: "mycloud"
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @group_categories = @categories.group_by{|cate|cate.parent_cate_id}
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
    @option_parent_category = option_parent_category
  end

  def create
    @category = Category.new(category_params)
    @option_parent_category = option_parent_category

    if @category.save
      redirect_to action: "index"
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
    @option_parent_category = option_parent_category
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to action: "index"
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    Category.where(parent_cate_id: params[:id]).destroy_all
  
    redirect_to action: "index"
  end

  private
  def option_parent_category
    Category.where(parent_cate_id:[nil,true]).collect{ |p| [ p.name, p.id ] }
  end


  private
    def category_params
      params.require(:category).permit(:name, :parent_cate_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
      @products = Product.joins(:category).paginate(page: params[:page], per_page: 5)
  end
  def show
    @product = Product.find(params[:id])
  end

  def new
      @product = Product.new
      @category = Category.all
  end

  def create
      @product = Product.new(product_params)
     
      if @product.save
        redirect_to action: "index"
      else
        render :new
      end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to action: "index"
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to action: "index"
  end
  
  private
      def product_params
        params.require(:product).permit(:name, :category_id)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
  <div>
    <%= form.label :name, 'Category Name', class:"form-label" %><br>
    <%= form.text_field :name , class:"form-control"%>
    <% category.errors.full_messages_for(:name).each do |message| %>
      <div class="alert alert-danger"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :parent_cate_id, 'Parent Category', class:"form-label" %><br>
    <%= form.select :parent_cate_id, @option_parent_category,
    {:prompt => "--Parent Category--"},
    {:class => "form-select"}  
    %>
      <% category.errors.full_messages_for(:parent_cate_id).each do |message| %>
      <div class="alert alert-danger"><%= message %></div>
    <% end %>
  </div>
  <br>
  <div>
    <%= form.submit "Submit" , class:"btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render "form", category: @category, option_parent_category: @option_parent_category %>

app/views/categories/index.html.erb
<h1>Category List</h1>
<%if @group_categories[nil]%>
<table class="table">
<thead>
  <tr>
    <td>#</td>
    <td>Name</td>
    <td>Children</td>
    <td>Action</td>
  </tr>
</thead>
<tbody>
<% @group_categories[nil].each do |category| %>
  <tr>
    <td><%= category.id %></td>
    <td><%= link_to category.name, category %></td>
    <td>
      <%if @group_categories[category.id]%>
        <% @group_categories[category.id].each do |children| %>
          <%= link_to children.name, edit_category_path(children) %> 
          <%if children != @group_categories[category.id].last%>
          ,
          <%end%>
        <%end%>
      <%else%>
         -
      <%end%>
    </td>
    <td>
    <%= link_to "แก้ไข", edit_category_path(category) %> |
    <%= link_to "ลบ", category_path(category),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
    </td>    
  </tr>
<% end %>
</tbody>
</table>
<%else%>
  <div>Empty Category</div>
  <br>
<%end%>
<%= link_to "Add Category", new_category_path, class:"btn btn-primary" %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render "form", category: @category, option_parent_category: @option_parent_category %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<p><%= @category.parent_cate_id %></p>

<ul>
  <li><%= link_to "Edit", edit_category_path(@category) %></li>
  <li><%= link_to "Destroy", category_path(@category),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCloudProductSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: product do |form| %>
  <div class="mb-3">
    <%= form.label :name, class:"form-label" %><br>
    <%= form.text_field :name, class:"form-control" %>
    <% product.errors.full_messages_for(:name).each do |message| %>
      <div class="alert alert-danger"><%= message %></div>
    <% end %>
  </div>

    <div>
    <%= form.label :category_id, class:"form-label" %><br>
    <%= form.select :category_id, Category.all.collect { |p| [ p.name, p.id ] },{:prompt => "--Category--"},{
      :class => "form-select"
    }%>
    <% product.errors.full_messages_for(:category_id).each do |message| %>
    <div class="alert alert-danger"><%= message %></div>
    <% end %>
    <%= link_to "+ Add Category" , new_category_path %>
  </div> 
  <br>
  <div>
    <%= form.submit "Submit", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<h1>Product List</h1>

<table class="table">
<thead>
  <tr>
  <td>#</td>
  <td>Name</td>
  <td>Category</td>
  <td>Action</td>
  </tr>
</thead>
<tbody>
<% @products.each do |product| %>
  <tr>
    <td><%=product.id%></td>
    <td><%= link_to product.name, product %></td>
    <td><%=product.category.name%></td>
    <td>
    <%= link_to "แก้ไข" , edit_product_path(product) %> | 
    <%= link_to "ลบ", product_path(product),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
    </td>
  </tr>
  <% end %>
</tbody>
</table>
<div class="digg_pagination" style="float:right">
  <div class="page_info">
    <%= page_entries_info @products %>
  </div>
  <%= will_paginate @products, :container => false %>
</div>

<%= link_to "Add Product" , new_product_path, class:"btn btn-primary" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form", product: @product %>

app/views/products/show.html.erb
<h1>
  <%= @product.name %>
</h1>

<ul>
  <li>
    <%= link_to "Edit" , edit_product_path(@product) %>
  </li>
  <li>
    <%= link_to "Destroy" , product_path(@product), method: :delete, data: { confirm: "Are you sure?" } %>
  </li>
</ul>